spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa-nativequery-problem
    username: jpa-nativequery-problem
    password: jpa-nativequery-problem
